debug: false
smartcloud:
    domain: "gz.sc.zhitingtech.com"
    tls: true
    grpc_port: 6666

smartassistant:
    host: 0.0.0.0
    port: 37965
    database:
        driver: "sqlite"
    host_runtime_path: "/mnt/data/zt-smartassistant"
    runtime_path: "/mnt/data/zt-smartassistant" # runtime_path 为 smartassistant 容器中运行时目录
    docker_registry: "zt.registry.zhitingtech.com"

extension:
    grpc_port: 9666